# -*- coding: utf-8 -*-
{
    'name': 'Valuation layer by location',
    'version': '13.0.1.1.0',
    'author': 'Ganemo',
    'website': 'https://www.ganemo.co',
    'description': """
In Odoo it is easy to enter to check what the current value of each product is by location, but there is no record of the value at a certain cut-off date.
When installing this module, when updating the cost from the product file, or when the costing method is changed, instead of generating a single 
"Stock Valuation" (stock.valuation.layer) as currently generated by Odoo, instead, as many stock valuations are generated as there are locations in Odoo.
Also create these fields in the "Stock Valuation" record (stock.valuation.layer), create these fields:
“Final balance amount” (qty_final_balance)
“Unit Cost of Ending Balance” (unit_cost_final_balance)
"Total Cost of Ending Balance" (total_cost_ending_balance)
"Place"
These fields are completed with the information of the quants, which allows us to keep a record of the valuation of each product by location.
    """,
    'depends': ['stock_account'],
    'data': [
        'security/stock_security.xml',
        'views/stock_views.xml'
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'currency': 'USD',
    'price': 35.00
}
